/**
 * KV storage for Telegram ↔ wallet linking.
 *
 * Keys:
 *   tg:link:wallet:{wallet}      → telegramId (string)
 *   tg:link:tgid:{telegramId}    → wallet (string)
 *   tg:code:{code}               → { telegramId, telegramUsername, expiresAt }
 */
import { kvGet, kvSet } from '@/lib/kv-store';

const CODE_TTL_SECONDS = 600; // 10 minutes

export type TelegramLink = {
  telegramId: string;
  telegramUsername: string | null;
  wallet: string;
  linkedAt: number;
};

export type TelegramLinkCode = {
  telegramId: string;
  telegramUsername: string | null;
  expiresAt: number;
};

// ── Link code (generated by /start in bot, consumed by web link page) ──

export async function setTelegramLinkCode(
  code: string,
  telegramId: string,
  telegramUsername: string | null
): Promise<void> {
  const value: TelegramLinkCode = {
    telegramId,
    telegramUsername,
    expiresAt: Date.now() + CODE_TTL_SECONDS * 1000,
  };
  await kvSet(`tg:code:${code}`, value);
}

export async function getTelegramLinkCode(
  code: string
): Promise<TelegramLinkCode | null> {
  const value = await kvGet<TelegramLinkCode>(`tg:code:${code}`);
  if (!value) return null;
  if (Date.now() > value.expiresAt) return null;
  return value;
}

export async function deleteTelegramLinkCode(code: string): Promise<void> {
  await kvSet(`tg:code:${code}`, null);
}

// ── Bidirectional wallet ↔ telegramId lookup ──

export async function getTelegramLinkByWallet(
  wallet: string
): Promise<TelegramLink | null> {
  return kvGet<TelegramLink>(`tg:link:wallet:${wallet.toLowerCase()}`);
}

export async function getTelegramLinkByTgId(
  telegramId: string
): Promise<TelegramLink | null> {
  return kvGet<TelegramLink>(`tg:link:tgid:${telegramId}`);
}

export async function setTelegramLink(
  wallet: string,
  telegramId: string,
  telegramUsername: string | null
): Promise<void> {
  const normalizedWallet = wallet.toLowerCase();

  // Remove any previous link for this wallet
  const existingByWallet = await getTelegramLinkByWallet(normalizedWallet);
  if (existingByWallet && existingByWallet.telegramId !== telegramId) {
    await kvSet(`tg:link:tgid:${existingByWallet.telegramId}`, null);
  }

  // Remove any previous link for this Telegram account
  const existingByTg = await getTelegramLinkByTgId(telegramId);
  if (existingByTg && existingByTg.wallet !== normalizedWallet) {
    await kvSet(`tg:link:wallet:${existingByTg.wallet}`, null);
  }

  const link: TelegramLink = {
    telegramId,
    telegramUsername,
    wallet: normalizedWallet,
    linkedAt: Date.now(),
  };

  await kvSet(`tg:link:wallet:${normalizedWallet}`, link);
  await kvSet(`tg:link:tgid:${telegramId}`, link);
}

export async function removeTelegramLinkByWallet(wallet: string): Promise<void> {
  const link = await getTelegramLinkByWallet(wallet.toLowerCase());
  if (!link) return;
  await kvSet(`tg:link:wallet:${link.wallet}`, null);
  await kvSet(`tg:link:tgid:${link.telegramId}`, null);
}
